### ISSUE TITLE
Trouble linking in framework 

### ISSUE THREAD

**Issue by rouxdoo** [robreuss/ElementalController#1]
I’ll preface by saying that these things are new to me.

Client side - I got Carthage installed and after Carthage update I had binarys in my Xcode project folder. The ElementController_iOS binary is embedded and syntax checking and completion are working as expected as I poke at some example code. It builds successfully but won’t run. I suspect I’m failing to add the framework to the app target:

dyld: Library not loaded: @rpath/ElementalController_iOS.framework/ElementalController_iOS
  Referenced from: /Users/ianjones/Library/Developer/CoreSimulator/Devices/C8793AA9-A725-48A8-8E85-179A8D35D303/data/Containers/Bundle/Application/3AA2B938-DE11-4338-A8F5-986C2C1CDD53/elemental-test.app/elemental-test
  Reason: image not found

Server side - I see everything linking in when I use swift package update but when I go to build it says  

pi@raspberrypi:~/led-control $ ls
Package.resolved  Package.swift  README.md  Sources  Tests
pi@raspberrypi:~/led-control $ swift build
Compile Swift Module 'led_control' (1 sources)
/home/pi/led-control/Sources/led-control/main.swift:1:8: error: no such module 'ElementalController'
import ElementalController
       ^
warning: dependency 'Socket' is not used by any target
warning: dependency 'SwiftyGPIO' is not used by any target
error: terminated(1): /usr/bin/swift-build-tool -f /home/pi/led-control/.build/debug.yaml main output

**Comment by rouxdoo** [comment]
Ok, great - adding Socket to linked binary in Xcode did the trick. I can’t test anything yet but it builds and runs in a Simulator so I think that’s fixed. At least until I can get server-side going to start doing stuff.

I won’t plan on pushing anything into your git at this point because...well, I’m pretty git clueless. If I can get my head around a basic test build then I’ll be happy to try helping.

Server: I was playing around learning SPM and got myself to a hello world executable on the pi but couldn’t integrate ElementalC.... so...

With a fresh clone of your git on my pi I tried to “swift package update && swift build” which was errors galore. I feel like I’m missing something basic - starting with how to use Xcode for the server build...been using nano via ssh. Stupid IDE’s have ruined my brain for thinking ;)

**Comment by robreuss** [comment]
Note, the errors galore may be partly, mostly or all compiler "warnings" rather than show-stopping "errors".  Let me know about what errors you see, if any.  

Glad you got it compiling in Xcode!

Hopefully if you add an `import ElementalController` to the top of your hello world, Swift won't complain when you run it.  

Unfortunately, no IDE for server-side Swift development.  If you get Samba setup on your Pi, then you could use Xcode to at least edit your Swift files, or Visual Studio Code if you prefer that.  Works pretty well, but you're still issuing the commands via ssh for compiling and running.  These are the key SPM commands:

```
swift package init --type executable // will create a file hierarchy for you for a new app
swift package resolve // will resolve dependencies relative to your Package.swift file
swift package update // will fetch and compile dependencies 
swift build
swift run // Will both build and run
```
I'm available to help.  Keep me posted!

**Comment by rouxdoo** [comment]
samba share for editing - thumbs up. Thanks, that will help.

Created a new project folder. If I can get a basic stub of a server project file going I think I can put this together. Sorry, I’m dense.

pi@raspberrypi:~/test-server $ swift package init --type executable
Creating executable package: test-server
error: a manifest file already exists in this directory
pi@raspberrypi:~/test-server $ ls -a
.  ..  Package.swift
pi@raspberrypi:~/test-server $ rm Package.swift 
pi@raspberrypi:~/test-server $ swift package init --type executable
Creating executable package: test-server
Creating Package.swift
Creating README.md
Creating .gitignore
Creating Sources/
Creating Sources/test-server/main.swift
Creating Tests/
pi@raspberrypi:~/test-server $ cp ../elemental/
._.DS_Store          .DS_Store            ElementalController/ 
pi@raspberrypi:~/test-server $ cp ../elemental/ElementalController/Package.swift .
pi@raspberrypi:~/test-server $ ls
Package.swift  README.md  Sources  Tests
pi@raspberrypi:~/test-server $ swift package resolve
Fetching https://github.com/IBM-Swift/BlueSocket.git
Fetching https://github.com/Bouke/NetService.git
Fetching https://github.com/Bouke/Cdns_sd.git
Fetching https://github.com/apple/swift-package-manager.git
Cloning https://github.com/Bouke/NetService.git
Resolving https://github.com/Bouke/NetService.git at 0.5.0
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolving https://github.com/IBM-Swift/BlueSocket.git at 1.0.43
Cloning https://github.com/Bouke/Cdns_sd.git
Resolving https://github.com/Bouke/Cdns_sd.git at 1.0.0
Cloning https://github.com/apple/swift-package-manager.git
Resolving https://github.com/apple/swift-package-manager.git at 0.3.0
pi@raspberrypi:~/test-server $ swift package update
Updating https://github.com/IBM-Swift/BlueSocket.git
Updating https://github.com/Bouke/NetService.git
Updating https://github.com/Bouke/Cdns_sd.git
Updating https://github.com/apple/swift-package-manager.git
Everything is already up-to-date
pi@raspberrypi:~/test-server $ swift build
warning: target 'ElementalController' in package 'ElementalController' contains no valid source files
'ElementalController' /home/pi/test-server: error: target 'ElementalController' referenced in product 'ElementalController' could not be found

**Comment by robreuss** [comment]
Your Package.swift file should look something like this in order to get ElementalController showing up in your project (along with SwiftyGPIO if you want that).  Not sure where that last warning is coming from.

```
import PackageDescription

let package = Package(
    name: "MyProjectName",
    dependencies: [
        // Dependencies declare other packages that this package depends on.

         .package(url: "https://github.com/uraimo/SwiftyGPIO.git", from: "1.0.0"),
         .package(url: "https://github.com/robreuss/ElementalController.git", .branch("develop")),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "MyProjectName",
            dependencies: ["SwiftyGPIO", "ElementalController"]),
    ]
)
```

**Comment by rouxdoo** [comment]
There we go. Building and running - I just copy/pasted your example server-side code and it ran. I assume I need to run a listen loop and detach so it persists but I think I can google that up tomorrow.

**Comment by robreuss** [comment]
This seems to be working well for me and my guess is that it is probably recommended over the approach above.  Again as before, MainProcess() is the primary class.  By passing its instance variable process into the closure, a reference is maintained until the extended is returned from - I'm not clear how that happens.  Here's the method at hand: [https://developer.apple.com/documentation/swift/1541033-withextendedlifetime](https://developer.apple.com/documentation/swift/1541033-withextendedlifetime)

```
var process = MainProcess()
process.setupHandlers()

withExtendedLifetime((process)) {
    RunLoop.main.run()
}
```

**Comment by robreuss** [comment]
exit(0) will exit from withExtendedLifetime, if you should need to shutdown on command.

**Comment by rouxdoo** [comment]
Sorry, Rob - not ignoring you. RealWork©️ took it’s toll on me today - just got home. Stupid work....

**Comment by robreuss** [comment]
I can understand that!

**Comment by rouxdoo** [comment]
I get "Illegal Instruction" and stop when I add your withExtendedLifetime() block. without it program execution just ends (because I'm not looping or blocking). I think I'm having trouble understanding where to go into listen mode. I would have assumed that publish(onPort: 0) would be a blocking network call which waits for network activity.

here is my main.swift:

import ElementalController
import Foundation

class MainProcess {
    // Element identifiers must be the same as the client side
    enum ElementIdentifier: Int8 {
        
        case brightness = 1
        case backlight = 2
        
    }
    
    var elementalController = ElementalController()
    func startup() {
        elementalController.setupForService(serviceName: "screen_control", displayName: "My server")
        
        elementalController.service.events.onDeviceConnected.addHandler(
            handler: { _, device in
                // Attach elements to client device...
                let brightness = device.attachElement(
                    Element(identifier: ElementIdentifier.brightness.rawValue,
                            displayName: "Brightness",
                            proto: .tcp,
                            dataType: .Float))
                
                let backlight = device.attachElement(
                    Element(identifier: ElementIdentifier.backlight.rawValue,
                            displayName: "Backlight",
                            proto: .tcp,
                            dataType: .Float))
                
                brightness.handler = { element, _ in
                    logDebug("Server received a brightness element: \(element.value)")
                }
                
                backlight.handler = { element, _ in
                    logDebug("Server received a backlight element: \(element.value)")
                }
                
        })
        
        // Setting this to port "0" will automatically select an available port
        elementalController.service.publish(onPort: 0)
        print("started...")
    }
}

var process = MainProcess()
process.startup()
withExtendedLifetime((process)) {
    RunLoop.main.run()
}

**Comment by robreuss** [comment]
Try this look instead of extended lifetime:

```
while true {
    RunLoop.current.run(mode: RunLoopMode.defaultRunLoopMode, before: Date(timeIntervalSinceNow: 0.1))
}
```

**Comment by rouxdoo** [comment]
Illegal instruction and quit. I don't know how to figure out what I don't know here.

If I were doing this without the framework I would bind a socket then call listen() which would block until data came in then I would fire off a thread to handle it and go back to listen(). Start it up and there is a running server.

Is there something I'm supposed to be doing after publish()?

...Linking ./.build/armv7-unknown-linux-gnueabihf/debug/test-server
pi@raspberrypi:~/test-server $ ./.build/armv7-unknown-linux-gnueabihf/debug/test-server
[EC] Service event types initialized
[EC] {screen_control} Server initialized
[EC] {screen_control} Initializing Service Device
[EC] {screen_control} Initializing Service Device
[EC] {screen_control} [tcp] Initializing TCPServer
service.publish onPort...just ran
pi@raspberrypi:~/test-server $

**Comment by robreuss** [comment]
I don't think it is related but just wanted to confirm you installed `sudo apt install libavahi-compat-libdnssd-dev` on the Pi side of things.

Not sure about the illegal instruction - did that occur just after the part of your log above ends?  

As a general matter, after you publish you do nothing related to the framework.  That is the purpose of the handlers - once a client device connects (deviceConnected) the handler for that is triggered.  It is a non-blocking.  And then once those devices send data, your element-specific handlers fire.

**Comment by robreuss** [comment]
I'm here tinkering with my electronics projects so please don't hesitate to send questions - I'll be right on them.

**Comment by rouxdoo** [comment]
Yes, I installed the lib.
The above log shows it running with the while() loop commented out. Illegal instruction happens with call to RunLoop either way you described.

The only function of my “server” at this point is to register the handlers to listen. I have no other work to do so I have no program loop to run with a non-blocking function already executed - program execution simply ends. I suspect illegal instruction is happening because there’s nothing left to do?

**Comment by robreuss** [comment]
Could you post some code?

**Comment by robreuss** [comment]
One thing I forgot to add to the README is that hosts need to have ".local" as a suffix to their hostname.  That would not explain your illegal instruction but it is necessary for connections.

**Comment by rouxdoo** [comment]
Lol, the entirety of my code is the main.swift I posted above. I finally glanced at the markdown style guide so as to hurt your eyes a bit less as you peruse my cringe-y code.

```swift
import ElementalController
import Foundation

class MainProcess {
    // Element identifiers must be the same as the client side
    enum ElementIdentifier: Int8 {
        
        case brightness = 1
        case backlight = 2
        
    }
    
    var elementalController = ElementalController()
    func startup() {
        elementalController.setupForService(serviceName: "screen_control", displayName: "My server")
        
        elementalController.service.events.onDeviceConnected.addHandler(
            handler: { _, device in
                // Attach elements to client device...
                let brightness = device.attachElement(
                    Element(identifier: ElementIdentifier.brightness.rawValue,
                            displayName: "Brightness",
                            proto: .tcp,
                            dataType: .Float))
                
                let backlight = device.attachElement(
                    Element(identifier: ElementIdentifier.backlight.rawValue,
                            displayName: "Backlight",
                            proto: .tcp,
                            dataType: .Float))
                
                brightness.handler = { element, _ in
                    logDebug("Server received a brightness element: \(element.value)")
                }
                
                backlight.handler = { element, _ in
                    logDebug("Server received a backlight element: \(element.value)")
                }
                
        })
        
        // Setting this to port "0" will automatically select an available port
        elementalController.service.publish(onPort: 0)
        print("service.publish onPort...just ran")
    }
}

var process = MainProcess()
process.startup()

//while true {
//    print("begin looping...")
//    RunLoop.current.run(mode: RunLoopMode.defaultRunLoopMode, before: Date(timeIntervalSinceNow: 0.1))
//    print("end of loop")
//}

//withExtendedLifetime((process)) {
//    RunLoop.main.run()
//}
```

**Comment by rouxdoo** [comment]
> One thing I forgot to add to the README is that hosts need to have ".local" as a suffix to their hostname. That would not explain your illegal instruction but it is necessary for connections.

I read that when I scanned your code but assume that relates to discovery.

**Comment by robreuss** [comment]
Here's working code based on the README code.  Not that for the runLoop stuff to work you need to import Dispatch like I do.  

```swift

import ElementalController
import Foundation
import Dispatch
import Glibc

class MainProcess {
    
    // Element identifiers must be the same as the client side
    enum ElementIdentifier: Int8 {
        
        case brightness = 1
        case backlight = 2
        
    }
    func startup() {
        var elementalController = ElementalController()
        elementalController.setupForService(serviceName: "screen_control", displayName: "My server")
        
        elementalController.service.events.onDeviceConnected.addHandler(
            handler: { _, device in
                
                // Attach elements to client device...
                let brightness = device.attachElement(
                    Element(identifier: ElementIdentifier.brightness.rawValue,
                            displayName: "Brightness",
                            proto: .tcp,
                            dataType: .Float))
                
                let backlight = device.attachElement(
                    Element(identifier: ElementIdentifier.backlight.rawValue,
                            displayName: "Backlight",
                            proto: .tcp,
                            dataType: .Float))
                
                brightness.handler = { element, _ in
                    logDebug("Server received a brightness element: \(element.value)")
                }
                
                backlight.handler = { element, _ in
                    logDebug("Server received a backlight element: \(element.value)")
                }
                
        })
        
        // Setting this to port "0" will automatically select an available port
        elementalController.service.publish(onPort: 0)
    }
    

}


var process = MainProcess()

process.startup()

while true {
    RunLoop.current.run(mode: RunLoopMode.defaultRunLoopMode, before: Date(timeIntervalSinceNow: 0.1))
}
```

**Comment by robreuss** [comment]
What operating system?

**Comment by robreuss** [comment]
Try making this a class level variable instead...it will retain and not deinitialize like your log indicates.

```swift
class MainProcess {
    var elementalController = ElementalController()
```

**Comment by robreuss** [comment]
Sorry I missed that.  I'll put all of this into the readme so it's super-helpful we're going through this.  I tried to keep it simple but instead should have just made it a file's worth of working code.

**Comment by rouxdoo** [comment]
Raspian stretch.

**Comment by rouxdoo** [comment]
same output without the "deinitialize" log message
Illegal instruction

**Comment by robreuss** [comment]
Do you recall if you installed a build specific to Rasbian?  

If not, there's a link to 4.1.3 at the top of this page: https://www.uraimo.com/2018/06/13/A-big-update-on-Swift-4-1-2-for-raspberry-pi-zero-1-2-3/

You can get 4.1.2 via Apt here (uninstall first):
https://swift-arm.com/2018/08/02/swift-4-1-2-updated-for-raspberrypi-2-3/

**Comment by rouxdoo** [comment]
I did indeed install the Raspbian-specific version. I used apt-get as directed in the second link above.

pi@raspberrypi:~ $ swift --version
Swift version 4.1.1 (swift-4.1.1-RELEASE)
Target: armv7-unknown-linux-gnueabihf
pi@raspberrypi:~ $ sudo apt-get install swift-4.1-RPi23-RaspbianStretch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'swift-4.1-rpi23-raspbianstretch' for glob 'swift-4.1-RPi23-RaspbianStretch'
swift-4.1-rpi23-raspbianstretch is already the newest version (4.1.2).
The following packages were automatically installed and are no longer required:
  libcurl3-nss lxkeymap python-cairo python-gobject python-gobject-2 python-gtk2 python-xklavier
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $

**Comment by robreuss** [comment]
I'm checking if it runs for me on Raspbian.

**Comment by robreuss** [comment]
I setup a Stretch installation along with the Swift 4.1.1 you're running and reproduced the error!  

I installed Swift 4.1.3 for Stretch from here and all is well:
https://www.dropbox.com/s/e257cvg23ghe2dt/swift-4.1.3-RPi23-RaspbianStretch.tgz?dl=0

Ran a smoke test with no problem.  Updating the requirements in the README.

**Comment by rouxdoo** [comment]
That did the trick. now the server sets up and keeps running. I could background it and run as a daemon if desired.

Back to the (iOS) client - I can connect and see it communicating so I know they're talking. Right now I'm using the examples you have for client and server event handlers. I haven't tried to implement any logic or actual actions behind them but let me know if a (client) crash is unexpected given that:

```log
[EC] Service event types initialized
[EC] {screen_control} Browsing for service of type: _screen_control._tcp. in domain: local.
[EC] {screen_control} Browser found service of type _screen_control._tcp.
[EC] {screen_control} Resolving service _screen_control._tcp....
[EC] {screen_control} Browser successfully resolved address: raspberrypi.local.: 34397, service name: "My server"
[EC] {screen_control} Initializing Server Device
[EC] {screen_control} [tcp] Element added: UDP Identifier (system) (UInt8)
[EC] {screen_control} [tcp] Element added: Device Name (system) (String)
[EC] {screen_control} [tcp] Element added: Shutdown Message (system) (String)
[EC] {screen_control} [tcp] Element added: Brightness (Float)
[EC] {screen_control} [tcp] Element added: Backlight (Float)
[EC] {screen_control} Connecting to service
[EC] {screen_control} [udp] Initializing UDP client for ip address raspberrypi.local. on port 34397
[EC] {screen_control} Stopping browsing for screen_control
[EC] {screen_control} Connecting to server at raspberrypi.local. 34397
[EC] {screen_control} [tcp] Device received connect success
[EC] {screen_control} [tcp] Element added: Device Name (system) (String)
[EC] {screen_control} TCP Client connected to raspberrypi.local.
[EC] {screen_control} Received UDP identififer from raspberrypi.local.: 1
[EC] {screen_control} Notifying client that they are connected.
[EC] <<< ERROR >>> Attempted to encode Float element "Brightness" failed - wrong type
Message from debugger: The LLDB RPC server has crashed. The crash log is located in ~/Library/Logs/DiagnosticReports and has a prefix 'lldb-rpc-server'. Please file a bug and attach the most recent crash log.
Fatal error: : file /Users/ianjones/Desktop/elemental-test/Carthage/Checkouts/ElementalController/Sources/ElementalController/Elements.swift, line 250
2019-01-11 17:17:39.938358-0600 elemental-test[83404:2066762] Fatal error: : file /Users/ianjones/Desktop/elemental-test/Carthage/Checkouts/ElementalController/Sources/ElementalController/Elements.swift, line 250
```

**Comment by robreuss** [comment]
Are you passing a value that is not explicitly a Float to the Brightness element?  Non-integers are implicitly doubles unless you explicitly type them, for example:

```swift
element.value = Float(5.0)
```

**Comment by rouxdoo** [comment]
Frankly, I'm somewhat unclear on how to pass anything other then as specified in the client/server examples in your readme. I figure I can change float to bool (or whatever) as long as I do it the same on client and server ends, right?

Right now I'm trying to just push a value from client to server.
```swift
import UIKit
import ElementalController_iOS

class ViewController: UIViewController {

    // Define a integer identifier for elements
    enum ElementIdentifier: Int8 {
        
        case brightness = 1
        case backlight = 2
        
    }
    var elementalController = ElementalController()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        elementalController.setupForBrowsingAs(deviceNamed: "ian")
        elementalController.browser.events.onFoundServer.handler { serverDevice in
            // Attach elements to server...
            _ = serverDevice.attachElement(
                Element(identifier: ElementIdentifier.brightness.rawValue,
                        displayName: "Brightness",
                        proto: .tcp,
                        dataType: .Float))
            
            _ = serverDevice.attachElement(
                Element(identifier: ElementIdentifier.backlight.rawValue,
                        displayName: "Backlight",
                        proto: .tcp,
                        dataType: .Float))
            
            // Once connected, you can send elements to the server...
            serverDevice.events.onConnect.handler = {serverDevice in
                
                if let brightness = serverDevice.getElementWith(identifier: ElementIdentifier.brightness.rawValue) {
                    brightness.value = 0.0
                    _ = serverDevice.send(element: brightness)
                } else {
                    logError("Unable to find brightness element")
                }
            }
            // Finally, connect to the server!
            serverDevice.connect()
        }
        elementalController.browser.browse(serviceName: "screen_control")
    }
}
```

**Comment by robreuss** [comment]
My mistake in the sample code.  This...

```swift
brightness.value = 0.0
```
should be:
```swift
brightness.value = Float(0.0)
```

**Comment by rouxdoo** [comment]
Cool beans! I can send a value to the service and see it on the other end.
I assume the Element() :datatype must only be a defined ElementDataType, right?

Let me see if I can query the server for a value now...

**Comment by robreuss** [comment]
Great!  Phew.

Yes - ElementDataType, which should cover all types, integer, floating point, string and data.  With Data, of course, you can send anything you want.

Note, to do the communication in reverse, from client to server, it's just a matter of handlers on the server side and send commands on the client side, in case that wasn't obvious.

**Comment by robreuss** [comment]
I got something cool working.  Hooked up a HC-SR04 ultrasonic ranging module to my Pi and got that working using SwiftyGPIO.  I then implemented the framework as a client on the Pi and my iPhone as a server, and started having the Pi send distance data to the iPhone, and then I displayed that on a slider!  So you can hold the phone in front of the sensor, move it away, and see the slider move.  Love finding ways to put my framework to use.

**Comment by rouxdoo** [comment]
That is cool! Yeah, it’s really fun to make new things that didn’t exist until you made them.

**Comment by rouxdoo** [comment]
> Note, to do the communication in reverse, from client to server, it's just a matter of handlers on the server side and send commands on the client side, in case that wasn't obvious.

Ok, so am I getting it right that if I want to pass values bi-directionally I should implement client and server on both ends?

Example:
iOS query of pi value: iOS client sends query value to server on pi
then pi server handler makes call to:
pi client sends response value to server on iOS
then iOS server handler gets query

...or am I missing something?

**Comment by robreuss** [comment]
No need to implement a separate service.  The TCP handles bi-directional communication, and so to send from server to client:

1. On the server side, call `send` on an instance of the element after setting the value.  You can call `clientDevice!.getElementWith(identifier: yourElement)` to obtain the element for that specific connected device, if you're not just responding in the context of receiving the element.   

2. On the client side, setup a handler to provide you with an event when the server sends the element.  

Sorry if I made this sound more complicated than it is above.

Sorry if I made it sound more complicated than it is.

**Comment by rouxdoo** [comment]
Without some kind of API reference or more example code I won’t get this. I can now send a float from iOS to pi. Client to server. I can tell the server something from an iOS client.

I must say that this seems very robust as compared to a clunky ssh session with the associated overhead of authentication and string processing, etc. I like it.

Beyond the meet-and-greet between the two (in which I send said float) I need a code example of how the client requests a value from the server.

I’m sure my next gripe will be how do I pass values into the handler (closure) but I think I can google that one without bothering you.

I’m sorry if that sounds like “code for me, please” I just don’t understand the design so I can’t implement it without an example or documentation.

**Comment by rouxdoo** [comment]
Cooking with gas now!

I just needed to get a good nights sleep and shake off the work week. I added a control Element to send commands to the server which responds by sending return values to client as you described above. Hooked up the handlers and now I just need to do something with my new communication channel.

I think I’m there, thanks.

**Comment by robreuss** [comment]
Glad to hear the elements are flowing!  

I had to merge my Develop branch into Master.  There aren't huge changes, but some syntax and stability stuff.  If you avoid doing a `swift package update` for a while you can avoid them, but if you want to help with testing, here are the minor syntax changes.

I've decided against using Apple's format for events like:

 `onDeviceConnected ` is now `deviceConnected`
`onDeviceDisconnect` is now `deviceDisconnected`
`onFoundServer` is now `foundServer`

I don't know if you are already using it, but when a client successfully connects to a server, it gets an event and it can set a handler like this "serverDevice.events.connected.handler". 

When a server disappears the client will get a "serverDevice.events.deviceDisconnected.handler" call.

Also, I've turned handlers consistently into properties not methods.  "onDeviceConnect" was using this "addHandler" syntax:
```swift
elementalController.service.events.onDeviceConnected.addHandler(
    handler: { _, device in
...
```
and is now using this syntax, consistent with other handlers:
```swift
elementalController.service.events.deviceConnected.handler = { _, device in
```
Do let me know if you end up needing any other events!

Oh, one other thing.  The version you are on MAY be using IPv6.  I ran into some problems with it when I had my Raspberry acting like a client - it would get a connection refusal from my iOS devices.  When I changed it to IPv4 it works.  Because the whole situation is a bit shaky, although it defaults to IPv4, I created a class property for it:

```
ElementalController.protocolFamily = .inet // IPv4
ElementalController.protocolFamily = .inet6 // IPv6
```

FYI, here are other class properties set on the ElementalController singleton, nothing too interesting:

```swift
        ElementalController.loggerLogLevel = .Debug
        ElementalController.allowUDPService = true
        ElementalController.enableTransferAnalysis = true
        ElementalController.transferAnalysisFrequency = 10.0
        ElementalController.UDPBufferSize = 512 
        ElementalController.TCPBufferSize = 4096
```

**Comment by rouxdoo** [comment]
I appreciate the API pointers so I can play with your tool. The changes you described were trivial to make so I’m working off your master. I haven’t had any issues with IPv4/6 - frankly your abstraction of the network layer has made it plug-n-play as far as that’s concerned. I don’t even know or care if it’s talking over udp or tcp.

The framework is snappy! I’m liking it very much and it makes my ssh calls feel like sending a telegram vs speaking to someone.

My first suggestion for fostering others to utilize your framework is to come up with an install process for placing swift and dependencies on the pi so that it’s a one-script operation to get someone operational.

My second would be to include complete example client and server implementations that will give a user a starting point that is operational out of the box.

I might start working on #1 as a bundled part of my other project but just wanted to say thanks.

**Comment by robreuss** [comment]
I've polished the two example apps, installed by cloning and ran them and it all goes very smooth.  

The iOS app will build simply by running `carthage update` - no need to add any frameworks as they are already included in the project files.  Linux sample works on macOS as well.  I added a function to send motion data over UDP, just to give a sense of the performance.  Code is now commented.  I added tags to the repository so maybe it'll get a little traffic.  I'll wait for it to evolve more before I promote it (mainly to Raspberry Pi communities).  I've done an open source project before and my expectations are low for experiencing interest, in a healthy way.

**Comment by rouxdoo** [comment]
I just checked out your sample apps. Looks great! That will really help someone get up and running. I’m loving how responsive your framework is compared to my clunky ssh. Let me know when/where you announce your baby and I will show up to offer kudos and first-hand experience.

**Comment by robreuss** [comment]
Thank you sir!

**Comment by rouxdoo** [comment]
Rob,
Would you mind if I shared your most excellent framework with others? I’d like to push a small utility out which uses it (with accreditation and thanks, of course).

 -- 
Ian Jones
Cell: (214) 682-7918

**Comment by robreuss** [comment]
I'd be delighted.  Thanks Ian.  (I need to confirm that the sample apps still work - I'm not sure but I may have pushed a breaking change to the master branch.)

My robot vehicle, which is intended to demo the framework, is coming along nicely.  Having a bit of trouble with it's on-board compass in terms of accuracy but working through that.  I wrote up a little piece about it if you'd like to [take a look](https://medium.com/@robreuss/driving-a-raspberry-pi-based-robot-vehicle-using-motion-control-b9478ec0ae02).  I'll be adding video to the story as soon as I get some things nailed down.  Right now there's a tangle of wires going all over the place.

**Comment by robreuss** [comment]
Ian, there was a bit of a problem with the iOS sample app - addressed it and so those apps are ready to be tried by anyone who decides to check out the framework.  

So what is your utility?

**Comment by robreuss** [comment]
Cool!  
I'm very susceptible to feature creep, so I've been avoiding putting too much into it, preferring to leave it to the developer to layer on top of it higher levels of functionality like authentication.  BlueSocket has encryption so it's really just a matter of exposing and testing that.  I've been imagining that most uses of the framework would be LAN based with authentication/encryption would be less critical.  But I think you're right that I should get to encryption sooner rather than later.  I though about obfuscating UDP (an earlier version had it) by using a larger UDP client identifier (32 or 64 bits instead of the current byte) and rotating that by sending a new identifier over TCP.  What do you think of that?

It occurs to me that SSL/TLS can provide authentication, although I'm not fresh on the details of how to do that so the keys are tightly coupled.  It may be case that if I expose SSL/TLS it will provide strong authentication as an option in terms of how certs are created.

**Comment by rouxdoo** [comment]
Just FYI, when using your framework I had to add Socket framework to linked library and run script/build phase copy of ElemantalController to get a build. I just tried to push a build up to Apple and it seems that Socket framework also needs to be copied or it won’t be signed and Apple rejects the build. 

https://github.com/Carthage/Carthage/blob/5fd867c4895b4f59d70181dec169a1644f4430e3/README.md#if-youre-building-for-ios

Easy fix, but just as easy to forget.

 -- 
Ian Jones
Cell: (214) 682-7918

**Comment by robreuss** [comment]
Thanks!  Updated README.

**Comment by robreuss** [comment]
Per your last question (I think you are pointing to a good example of how authentication/authorization is complicated), this is why depending on SSL/TLS to provide authentication as-needed based on a scenario/developer to me is the best bet: it is implemented at the socket level by creating a configuration (before creating a socket) and then applying the configuration.  I could provide pass-through interface to the BlueSocket SSL/TLS module for configuration, and I would be responsible for applying the configuration to the socket when it's created. 

A framework-level authentication system would have a hard time including UDP in the scheme because it is connectionless, whereas SSL would be applicable.   

Here's the SSL/TLS module:
https://github.com/IBM-Swift/BlueSSLService

That's a great example about the fight bots - gamers are notorious about hacking and cheating!  And robots are a key use case.

**Comment by robreuss** [comment]
Ian, would you might taking a look at this possible change and tell me what you think?

https://github.com/robreuss/ElementalController/issues/2
