### ISSUE TITLE
Type-specific convenience methods for "value"

### ISSUE THREAD

**Issue by robreuss** [robreuss/ElementalController#2]
Current functionality returns an Any from the `value` property for an element, which means that the developer user has to downcast to the specific type required when getting the value, for example:

```let myValue = element.value as! Float```

Also, while setting the value does not require type casting (because the value is being set to Any, any typed value will do), setting the wrong typed value will lead to a run-time error.

By creating type-specific versions of the `value` property, such as `floatValue`, type safety will be enforced at compile time for both getting and setting, and make code more readable:

```let myValue = element.floatValue```

It wold be possible to do automatic casting for the decimal types.  For example, if the element data type is Int and the underlying value is an Int, the user could nevertheless obtain the value using `floatValue` and the value would be automatically cast to the desired type.  However, such an approach could lead to unintended consequences and errors, and undermines the compile time type safety this change offers.

**Comment by rouxdoo** [comment]
I think it would be very useful to have value get/set methods that eliminate the forced casts. I ran into a crash early on trying to set a float element from a Double without thinking about the underlying dataType. I think people will catch on easier if you can reference the ElementDataType enum in examples.
```
if element.dataType == .String { // ElementDataType enum
    myStr = element.value
}
```

On an unrelated note, I would love to see a Bool dataType. Yes, it’s trivial to use 1 and 0 or 0 and !0 but it just doesn’t feel very Swifty. I would like to forget about the transport and simply sling my variable across the chasm and have it reappear on the other side. I think that’s where you’re going with your convenience methods, right?

**Comment by robreuss** [comment]
I can't believe I forgot Bool!  It should have been there and I'll add it.

I've started moving forward with the type-specific value methods - I did a couple of types and updated some of my robot code and it is far more intuitive.  I have some good error handling setup - if you try to read from the `floatValue` method on an element with a Double datatype, it'll say something like "Attempt to read value using incorrect type method: using floatValue, should use doubleValue".  It throws a fatal error and displays that message in the code window and in the console.  

I need to decide if I'm going to keep the old `.value` method exposed, the one that sets/gets an Any.  It's still used under-the-hood but I don't see any reason to keep it.  If a developer needs an Any, she can cast her value to Any.

**Comment by rouxdoo** [comment]
I don’t see why you would keep the public Any if you’ve got get/set implemented. Make me think about my types so I don’t get lazy and crash ;)

I would appreciate a heads up before you push so I can update my server installer which clones your repo to build the pi companion component for my little app. I released an app update today which uses it.

**Comment by robreuss** [comment]
It's on the `develop` branch  if you'd be up for giving it a spin.  Your Cartfile would be changed to:

```github "robreuss/ElementalController" "develop"```

It includes the new type-specific value properties and a new Bool type.  The old `value` property is now "internal" so the compiler should tell you where you need to make changes.

**Comment by robreuss** [comment]
I noticed someplace where I put the "Any" type of the old `value` property to good use so I've added a new `anyValue`.

**Comment by robreuss** [comment]
@rouxdoo Ian, I think I'm ready to post to reddit about the framework!  I'm still going to emphasize its beta status.  If you could let me know when you're ready for me to merge develop into master that would be great!

**Comment by rouxdoo** [comment]
I don’t want to slow you down. How can I point my SPM Package.swift at your current master? I assume there is a way? I’m a git-idiot so sorry.
Can this:
`.package(url: "https://github.com/robreuss/ElementalController.git", .branch("master")),`
Be something like:
`.package(url: "https://github.com/robreuss/ElementalController.git", .version(“0.0.0.106”)),`
And I can catch up shortly?

**Comment by robreuss** [comment]
"master" branch is used by default, so your first package command is redundant.  To try the "develop" branch, just replace master with develop:
```
.package(url: "https://github.com/robreuss/ElementalController.git", .branch("develop")),
```
Thanks!

**Comment by rouxdoo** [comment]
I’m trying to make my server-side installer that’s already published continue pointing to what works now to avoid breaking things while I switch to develop to play with your changes. Currently my installer clones:
https://github.com/rouxdoo/SwiftServer
And then builds using your current master. Will this SPM dependency line make it continue to do so?
`// .package(url: "https://github.com/robreuss/ElementalController.git", .branch("master")),`
`.package(url: "https://github.com/robreuss/ElementalController.git", “0.0.106”),`

**Comment by robreuss** [comment]
My "develop" branch is out there for testing.  Once you're ready, I'll merge that into my "master" branch.  
So the approach I would think that makes sense is for you use a local setup first with a Package.swift that points to the "develop" branch, for testing.  The alternative to testing locally would be for you to create a branch for testing, and use a Package on that branch that points that points to my "develop" branch.  

I'm no expert at this either!  Happy to muddle through it with you.

**Comment by rouxdoo** [comment]
I think this does it:
`        .package(url: "https://github.com/robreuss/ElementalController.git", .exact("0.0.106")),
`
Now I think if you merge your develop into your master I can still point to the previous release until I'm ready to catch up.

**Comment by robreuss** [comment]
Ah, right.  Perfect!  I'll go ahead and merge.  Let me know if there's any problems that I can help with.

**Comment by rouxdoo** [comment]
Thanks for all your help. Ping me when you post - I want to give karma...least I can do for you :)

**Comment by robreuss** [comment]
Thanks!

Merging and publishing latest to "master" in the next couple of minutes.

Going to delete our other, very long issue thread.  If there's any info there you need, please grab it!  We should probably chat somewhere else.  Have a preference?

**Comment by rouxdoo** [comment]
I emailed you.
